version: '3.7'

services:
  bingo-app:
    networks:
      - bingo-network
    links:
      - bingo-db
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: bingo-app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
    depends_on:
      - bingo-db
  bingo-db:
    container_name: bingo-db
    networks:
      - bingo-network
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

networks:
  bingo-network:
    driver: bridge